# Generated by Django 6.0.6 on 2026-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=200)),
                ('user_email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
